spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  main:
    web-application-type: servlet
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  security:
    user:
      name: heavenhr
      password: password
      roles: USER
management:
  endpoints:
    web:
      base-path: /status
  server:
    port: 8081
    servlet:
      context-path:
server:
  port: 8082